[package]
name = "soundyrust"
version = "0.1.0"
edition = "2024"

[lints.clippy]
eq_op = "allow"

[dependencies]
bevy = "0.16.0-rc.5"
augmented-midi = "1.8.0"
itertools = "0.14.0"
rustysynth = "1.3.2"
num_enum = "0.7.3"

[lib]
name = "soundyrust"
path = "src/lib.rs"